export const APP_ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  LOGIN_LEGACY: "/sign",
  REGISTER: "/register",
  PROFILE: "/profile",
  SETTINGS: "/settings",
  CHANGE_PASSWORD: "/change-password",
  EVENTS: "/events",
  EVENT_DETAILS: "/events/:slug",
  DASHBOARD: "/dashboard",
  MY_TEAM: "/my-team",
  MY_REGISTRATIONS: "/my-registrations",
  MY_REGISTRATION_DETAILS: "/my-registrations/:id",
  MY_PAYMENTS: "/my-payments",
  MY_PAYMENT_DETAILS: "/my-payments/:id",
  ADMIN_USERS: "/admin/users",
  ADMIN_USER_DETAILS: "/admin/users/:id",
  ADMIN_TEAMS: "/admin/teams",
  ADMIN_TEAM_DETAILS: "/admin/teams/:id",
  ADMIN_EVENTS: "/admin/events",
  ADMIN_REGISTRATIONS: "/admin/registrations",
  ADMIN_PAYMENTS: "/admin/payments",
  ADMIN_HOME: "/admin",
  COSPLAY: "/cosplay",
  PAYMENT: "/payment",
  UNAUTHORIZED: "/unauthorized",
} as const;
